### PR TITLE
docs(package): Add instructions on installing external packages

### PR DESCRIPTION
**Pull request by iifeoluwa**

### CODE REVIEW

**Comment by louistiti** [comment]
[📝 [1.0.0-beta.2] How to install a Python module in the "Packages & Modules" section of the docs](https://trello.com/c/6IfPJaOm/237-%F0%9F%93%9D-100-beta2-how-to-install-a-python-module-in-the-packages-modules-section-of-the-docs)

**Comment by louistiti** [comment]
Hello @iifeoluwa,

Awesome, thanks! 👏

I'll merge it soon and do the French translation.

**Comment by iifeoluwa** [comment]
Nice! 

I'm considering contributing the Have I Been Pwned package, but I wanted to ask if there are other issues that have more priority that you wanted help with? I'd be happy to pick those up instead.

Great work on Leon!

**Comment by louistiti** [comment]
I've made the French translation and merged it.

Thanks! If you have a Raspeberry PI or similar hardware specs, it could be very helpful if you can take a look at https://github.com/leon-ai/leon/issues/28 and/or https://github.com/leon-ai/leon/issues/37 :smiley: 

Otherwise the Have I Been Pwned module (I guess it should be part of the Checker package) should be a funny one to work on.

**Comment by louistiti** [comment]
[📝 Instructions on installing external packages](https://trello.com/c/1AdsHBvz/252-%F0%9F%93%9D-instructions-on-installing-external-packages)

**Comment by iifeoluwa** [comment]
> I've made the French translation and merged it.
> 
> Thanks! If you have a Raspeberry PI or similar hardware specs, it could be very helpful if you can take a look at [leon-ai/leon#28](https://github.com/leon-ai/leon/issues/28) and/or [leon-ai/leon#37](https://github.com/leon-ai/leon/issues/37) 😃
> 
> Otherwise the Have I Been Pwned module (I guess it should be part of the Checker package) should be a funny one to work on.

Unfortunately, I don't have a hardware device I can get my hands on anytime soon, I'd have loved to help take care of those. 

It seems the Have I Been Pwned module isn't much of a priority at the moment, so I'll try to see if there's any other issue I can help tackle. I'd also be happy to look at others f you have any suggestions.

**Comment by louistiti** [comment]
I suppose you can start with the Have I Been Pwned module, it can be a good starting point, and then sightly increase the difficulty with more complexes one :smiley: 

Don't hesitate to create a feature request of what you'll work on in the [GitHub issues](https://github.com/leon-ai/leon/issues) of the main repository.

**Pull request merged**
